name: Sync Kindle Clippings to Notion

on:
  # schedule:
  #   - cron: "0 0 * * *"  # 每天0点执行一次
  workflow_dispatch:  # 手动触发
  push:
    branches:
      - main  # 触发条件为 push 到 main 分支

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore synced.log from cache
        uses: actions/cache@v4
        with:
          path: synced.log
          key: synced-log-cache
          restore-keys: |
            synced-log-cache

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sync script
        run: python sync_clippings.py

      - name: Save synced.log to cache
        uses: actions/cache@v4
        with:
          path: synced.log
          key: synced-log-cache
          save-always: true
