name: Sync Kindle Clippings to Notion

on:
  # schedule:
    # 每小时执行一次
    # - cron: '0 * * * *'
  workflow_dispatch: # 手动触发

jobs:
  sync_clippings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # 你可以选择任意的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Run the script
        run: |
          python sync_clippings.py  # 运行你的脚本
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}  # GitHub Secrets 用于存储 Notion Token
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}  # GitHub Secrets 用于存储 Notion Database ID
