name: Sync Kindle Clippings

on:
#  schedule:
#    - cron: '0 2 * * *'  # 每天凌晨 2 点运行
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests pytz

      - name: Restore synced.log
        uses: actions/download-artifact@v4
        with:
          name: synced-log
          path: .

      - name: Run sync script
        run: python sync_clippings.py
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

      - name: Save synced.log
        uses: actions/upload-artifact@v4
        with:
          name: synced-log
          path: synced.log
        continue-on-error: true  # 避免首次运行时出错
